services:
  postgres-search:
    image: postgres:16-alpine
    ports:
      - 1701:5432
    volumes:
      - uservice_search_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  uservice_search_postgres:
