// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-search/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockSearchMessagesService is an autogenerated mock type for the SearchMessagesService type
type MockSearchMessagesService struct {
	mock.Mock
}

type MockSearchMessagesService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchMessagesService) EXPECT() *MockSearchMessagesService_Expecter {
	return &MockSearchMessagesService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, note
func (_m *MockSearchMessagesService) Exec(ctx context.Context, note *models.SearchMessages) ([]*models.Message, error) {
	ret := _m.Called(ctx, note)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*models.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.SearchMessages) ([]*models.Message, error)); ok {
		return rf(ctx, note)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.SearchMessages) []*models.Message); ok {
		r0 = rf(ctx, note)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.SearchMessages) error); ok {
		r1 = rf(ctx, note)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchMessagesService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockSearchMessagesService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - note *models.SearchMessages
func (_e *MockSearchMessagesService_Expecter) Exec(ctx interface{}, note interface{}) *MockSearchMessagesService_Exec_Call {
	return &MockSearchMessagesService_Exec_Call{Call: _e.mock.On("Exec", ctx, note)}
}

func (_c *MockSearchMessagesService_Exec_Call) Run(run func(ctx context.Context, note *models.SearchMessages)) *MockSearchMessagesService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.SearchMessages))
	})
	return _c
}

func (_c *MockSearchMessagesService_Exec_Call) Return(_a0 []*models.Message, _a1 error) *MockSearchMessagesService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchMessagesService_Exec_Call) RunAndReturn(run func(context.Context, *models.SearchMessages) ([]*models.Message, error)) *MockSearchMessagesService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchMessagesService creates a new instance of MockSearchMessagesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchMessagesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchMessagesService {
	mock := &MockSearchMessagesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
