// Code generated by mockery v2.43.2. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	models "github.com/in-rich/uservice-search/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// MockUpsertMessageService is an autogenerated mock type for the UpsertMessageService type
type MockUpsertMessageService struct {
	mock.Mock
}

type MockUpsertMessageService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpsertMessageService) EXPECT() *MockUpsertMessageService_Expecter {
	return &MockUpsertMessageService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, message
func (_m *MockUpsertMessageService) Exec(ctx context.Context, message *models.UpsertMessage) (*models.Message, error) {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *models.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpsertMessage) (*models.Message, error)); ok {
		return rf(ctx, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UpsertMessage) *models.Message); ok {
		r0 = rf(ctx, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UpsertMessage) error); ok {
		r1 = rf(ctx, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpsertMessageService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockUpsertMessageService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - message *models.UpsertMessage
func (_e *MockUpsertMessageService_Expecter) Exec(ctx interface{}, message interface{}) *MockUpsertMessageService_Exec_Call {
	return &MockUpsertMessageService_Exec_Call{Call: _e.mock.On("Exec", ctx, message)}
}

func (_c *MockUpsertMessageService_Exec_Call) Run(run func(ctx context.Context, message *models.UpsertMessage)) *MockUpsertMessageService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.UpsertMessage))
	})
	return _c
}

func (_c *MockUpsertMessageService_Exec_Call) Return(_a0 *models.Message, _a1 error) *MockUpsertMessageService_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpsertMessageService_Exec_Call) RunAndReturn(run func(context.Context, *models.UpsertMessage) (*models.Message, error)) *MockUpsertMessageService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpsertMessageService creates a new instance of MockUpsertMessageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpsertMessageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpsertMessageService {
	mock := &MockUpsertMessageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
