// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/in-rich/uservice-search/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockSearchMessagesRepository is an autogenerated mock type for the SearchMessagesRepository type
type MockSearchMessagesRepository struct {
	mock.Mock
}

type MockSearchMessagesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchMessagesRepository) EXPECT() *MockSearchMessagesRepository_Expecter {
	return &MockSearchMessagesRepository_Expecter{mock: &_m.Mock}
}

// SearchMessages provides a mock function with given fields: ctx, teamID, rawQuery, limit, offset
func (_m *MockSearchMessagesRepository) SearchMessages(ctx context.Context, teamID string, rawQuery string, limit int, offset int) ([]*entities.Message, error) {
	ret := _m.Called(ctx, teamID, rawQuery, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchMessages")
	}

	var r0 []*entities.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*entities.Message, error)); ok {
		return rf(ctx, teamID, rawQuery, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*entities.Message); ok {
		r0 = rf(ctx, teamID, rawQuery, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) error); ok {
		r1 = rf(ctx, teamID, rawQuery, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchMessagesRepository_SearchMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMessages'
type MockSearchMessagesRepository_SearchMessages_Call struct {
	*mock.Call
}

// SearchMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - rawQuery string
//   - limit int
//   - offset int
func (_e *MockSearchMessagesRepository_Expecter) SearchMessages(ctx interface{}, teamID interface{}, rawQuery interface{}, limit interface{}, offset interface{}) *MockSearchMessagesRepository_SearchMessages_Call {
	return &MockSearchMessagesRepository_SearchMessages_Call{Call: _e.mock.On("SearchMessages", ctx, teamID, rawQuery, limit, offset)}
}

func (_c *MockSearchMessagesRepository_SearchMessages_Call) Run(run func(ctx context.Context, teamID string, rawQuery string, limit int, offset int)) *MockSearchMessagesRepository_SearchMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockSearchMessagesRepository_SearchMessages_Call) Return(_a0 []*entities.Message, _a1 error) *MockSearchMessagesRepository_SearchMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchMessagesRepository_SearchMessages_Call) RunAndReturn(run func(context.Context, string, string, int, int) ([]*entities.Message, error)) *MockSearchMessagesRepository_SearchMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchMessagesRepository creates a new instance of MockSearchMessagesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchMessagesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchMessagesRepository {
	mock := &MockSearchMessagesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
