// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDeleteMessageRepository is an autogenerated mock type for the DeleteMessageRepository type
type MockDeleteMessageRepository struct {
	mock.Mock
}

type MockDeleteMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteMessageRepository) EXPECT() *MockDeleteMessageRepository_Expecter {
	return &MockDeleteMessageRepository_Expecter{mock: &_m.Mock}
}

// DeleteMessage provides a mock function with given fields: ctx, teamID, messageID
func (_m *MockDeleteMessageRepository) DeleteMessage(ctx context.Context, teamID string, messageID string) error {
	ret := _m.Called(ctx, teamID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, teamID, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeleteMessageRepository_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockDeleteMessageRepository_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID string
//   - messageID string
func (_e *MockDeleteMessageRepository_Expecter) DeleteMessage(ctx interface{}, teamID interface{}, messageID interface{}) *MockDeleteMessageRepository_DeleteMessage_Call {
	return &MockDeleteMessageRepository_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, teamID, messageID)}
}

func (_c *MockDeleteMessageRepository_DeleteMessage_Call) Run(run func(ctx context.Context, teamID string, messageID string)) *MockDeleteMessageRepository_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDeleteMessageRepository_DeleteMessage_Call) Return(_a0 error) *MockDeleteMessageRepository_DeleteMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeleteMessageRepository_DeleteMessage_Call) RunAndReturn(run func(context.Context, string, string) error) *MockDeleteMessageRepository_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteMessageRepository creates a new instance of MockDeleteMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteMessageRepository {
	mock := &MockDeleteMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
