// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/in-rich/uservice-search/pkg/dao"
	entities "github.com/in-rich/uservice-search/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateReminderRepository is an autogenerated mock type for the UpdateReminderRepository type
type MockUpdateReminderRepository struct {
	mock.Mock
}

type MockUpdateReminderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateReminderRepository) EXPECT() *MockUpdateReminderRepository_Expecter {
	return &MockUpdateReminderRepository_Expecter{mock: &_m.Mock}
}

// UpdateReminder provides a mock function with given fields: ctx, authorID, reminderID, data
func (_m *MockUpdateReminderRepository) UpdateReminder(ctx context.Context, authorID string, reminderID string, data *dao.UpdateReminderData) (*entities.Reminder, error) {
	ret := _m.Called(ctx, authorID, reminderID, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReminder")
	}

	var r0 *entities.Reminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dao.UpdateReminderData) (*entities.Reminder, error)); ok {
		return rf(ctx, authorID, reminderID, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dao.UpdateReminderData) *entities.Reminder); ok {
		r0 = rf(ctx, authorID, reminderID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Reminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dao.UpdateReminderData) error); ok {
		r1 = rf(ctx, authorID, reminderID, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateReminderRepository_UpdateReminder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReminder'
type MockUpdateReminderRepository_UpdateReminder_Call struct {
	*mock.Call
}

// UpdateReminder is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - reminderID string
//   - data *dao.UpdateReminderData
func (_e *MockUpdateReminderRepository_Expecter) UpdateReminder(ctx interface{}, authorID interface{}, reminderID interface{}, data interface{}) *MockUpdateReminderRepository_UpdateReminder_Call {
	return &MockUpdateReminderRepository_UpdateReminder_Call{Call: _e.mock.On("UpdateReminder", ctx, authorID, reminderID, data)}
}

func (_c *MockUpdateReminderRepository_UpdateReminder_Call) Run(run func(ctx context.Context, authorID string, reminderID string, data *dao.UpdateReminderData)) *MockUpdateReminderRepository_UpdateReminder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*dao.UpdateReminderData))
	})
	return _c
}

func (_c *MockUpdateReminderRepository_UpdateReminder_Call) Return(_a0 *entities.Reminder, _a1 error) *MockUpdateReminderRepository_UpdateReminder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateReminderRepository_UpdateReminder_Call) RunAndReturn(run func(context.Context, string, string, *dao.UpdateReminderData) (*entities.Reminder, error)) *MockUpdateReminderRepository_UpdateReminder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateReminderRepository creates a new instance of MockUpdateReminderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateReminderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateReminderRepository {
	mock := &MockUpdateReminderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
