// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/in-rich/uservice-search/pkg/dao"
	entities "github.com/in-rich/uservice-search/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockUpdateNoteRepository is an autogenerated mock type for the UpdateNoteRepository type
type MockUpdateNoteRepository struct {
	mock.Mock
}

type MockUpdateNoteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateNoteRepository) EXPECT() *MockUpdateNoteRepository_Expecter {
	return &MockUpdateNoteRepository_Expecter{mock: &_m.Mock}
}

// UpdateNote provides a mock function with given fields: ctx, authorID, noteID, data
func (_m *MockUpdateNoteRepository) UpdateNote(ctx context.Context, authorID string, noteID string, data *dao.UpdateNoteData) (*entities.Note, error) {
	ret := _m.Called(ctx, authorID, noteID, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNote")
	}

	var r0 *entities.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dao.UpdateNoteData) (*entities.Note, error)); ok {
		return rf(ctx, authorID, noteID, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dao.UpdateNoteData) *entities.Note); ok {
		r0 = rf(ctx, authorID, noteID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dao.UpdateNoteData) error); ok {
		r1 = rf(ctx, authorID, noteID, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdateNoteRepository_UpdateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNote'
type MockUpdateNoteRepository_UpdateNote_Call struct {
	*mock.Call
}

// UpdateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - noteID string
//   - data *dao.UpdateNoteData
func (_e *MockUpdateNoteRepository_Expecter) UpdateNote(ctx interface{}, authorID interface{}, noteID interface{}, data interface{}) *MockUpdateNoteRepository_UpdateNote_Call {
	return &MockUpdateNoteRepository_UpdateNote_Call{Call: _e.mock.On("UpdateNote", ctx, authorID, noteID, data)}
}

func (_c *MockUpdateNoteRepository_UpdateNote_Call) Run(run func(ctx context.Context, authorID string, noteID string, data *dao.UpdateNoteData)) *MockUpdateNoteRepository_UpdateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*dao.UpdateNoteData))
	})
	return _c
}

func (_c *MockUpdateNoteRepository_UpdateNote_Call) Return(_a0 *entities.Note, _a1 error) *MockUpdateNoteRepository_UpdateNote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdateNoteRepository_UpdateNote_Call) RunAndReturn(run func(context.Context, string, string, *dao.UpdateNoteData) (*entities.Note, error)) *MockUpdateNoteRepository_UpdateNote_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateNoteRepository creates a new instance of MockUpdateNoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateNoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateNoteRepository {
	mock := &MockUpdateNoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
