// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/in-rich/uservice-search/pkg/dao"
	entities "github.com/in-rich/uservice-search/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockCreateNoteRepository is an autogenerated mock type for the CreateNoteRepository type
type MockCreateNoteRepository struct {
	mock.Mock
}

type MockCreateNoteRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateNoteRepository) EXPECT() *MockCreateNoteRepository_Expecter {
	return &MockCreateNoteRepository_Expecter{mock: &_m.Mock}
}

// CreateNote provides a mock function with given fields: ctx, authorID, noteID, data
func (_m *MockCreateNoteRepository) CreateNote(ctx context.Context, authorID string, noteID string, data *dao.CreateNoteData) (*entities.Note, error) {
	ret := _m.Called(ctx, authorID, noteID, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateNote")
	}

	var r0 *entities.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dao.CreateNoteData) (*entities.Note, error)); ok {
		return rf(ctx, authorID, noteID, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dao.CreateNoteData) *entities.Note); ok {
		r0 = rf(ctx, authorID, noteID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Note)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dao.CreateNoteData) error); ok {
		r1 = rf(ctx, authorID, noteID, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateNoteRepository_CreateNote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNote'
type MockCreateNoteRepository_CreateNote_Call struct {
	*mock.Call
}

// CreateNote is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - noteID string
//   - data *dao.CreateNoteData
func (_e *MockCreateNoteRepository_Expecter) CreateNote(ctx interface{}, authorID interface{}, noteID interface{}, data interface{}) *MockCreateNoteRepository_CreateNote_Call {
	return &MockCreateNoteRepository_CreateNote_Call{Call: _e.mock.On("CreateNote", ctx, authorID, noteID, data)}
}

func (_c *MockCreateNoteRepository_CreateNote_Call) Run(run func(ctx context.Context, authorID string, noteID string, data *dao.CreateNoteData)) *MockCreateNoteRepository_CreateNote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*dao.CreateNoteData))
	})
	return _c
}

func (_c *MockCreateNoteRepository_CreateNote_Call) Return(_a0 *entities.Note, _a1 error) *MockCreateNoteRepository_CreateNote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateNoteRepository_CreateNote_Call) RunAndReturn(run func(context.Context, string, string, *dao.CreateNoteData) (*entities.Note, error)) *MockCreateNoteRepository_CreateNote_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateNoteRepository creates a new instance of MockCreateNoteRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateNoteRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateNoteRepository {
	mock := &MockCreateNoteRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
