// Code generated by mockery v2.43.2. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/in-rich/uservice-search/pkg/dao"
	entities "github.com/in-rich/uservice-search/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockCreateReminderRepository is an autogenerated mock type for the CreateReminderRepository type
type MockCreateReminderRepository struct {
	mock.Mock
}

type MockCreateReminderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateReminderRepository) EXPECT() *MockCreateReminderRepository_Expecter {
	return &MockCreateReminderRepository_Expecter{mock: &_m.Mock}
}

// CreateReminder provides a mock function with given fields: ctx, authorID, reminderID, data
func (_m *MockCreateReminderRepository) CreateReminder(ctx context.Context, authorID string, reminderID string, data *dao.CreateReminderData) (*entities.Reminder, error) {
	ret := _m.Called(ctx, authorID, reminderID, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateReminder")
	}

	var r0 *entities.Reminder
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dao.CreateReminderData) (*entities.Reminder, error)); ok {
		return rf(ctx, authorID, reminderID, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *dao.CreateReminderData) *entities.Reminder); ok {
		r0 = rf(ctx, authorID, reminderID, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Reminder)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *dao.CreateReminderData) error); ok {
		r1 = rf(ctx, authorID, reminderID, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateReminderRepository_CreateReminder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReminder'
type MockCreateReminderRepository_CreateReminder_Call struct {
	*mock.Call
}

// CreateReminder is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID string
//   - reminderID string
//   - data *dao.CreateReminderData
func (_e *MockCreateReminderRepository_Expecter) CreateReminder(ctx interface{}, authorID interface{}, reminderID interface{}, data interface{}) *MockCreateReminderRepository_CreateReminder_Call {
	return &MockCreateReminderRepository_CreateReminder_Call{Call: _e.mock.On("CreateReminder", ctx, authorID, reminderID, data)}
}

func (_c *MockCreateReminderRepository_CreateReminder_Call) Run(run func(ctx context.Context, authorID string, reminderID string, data *dao.CreateReminderData)) *MockCreateReminderRepository_CreateReminder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*dao.CreateReminderData))
	})
	return _c
}

func (_c *MockCreateReminderRepository_CreateReminder_Call) Return(_a0 *entities.Reminder, _a1 error) *MockCreateReminderRepository_CreateReminder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateReminderRepository_CreateReminder_Call) RunAndReturn(run func(context.Context, string, string, *dao.CreateReminderData) (*entities.Reminder, error)) *MockCreateReminderRepository_CreateReminder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateReminderRepository creates a new instance of MockCreateReminderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateReminderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateReminderRepository {
	mock := &MockCreateReminderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
